
'use strict';
const KEY='moneytools_expense_pro_v1';
const expenseCats=['Food & Grocery','Housing','Transport','Bills & Utilities','Shopping','Health','Education','Entertainment','Loan & EMI','Travel','Other'];
const incomeCats=['Salary','Business','Freelance','Interest','Gift','Other Income'];
const allCats=[...new Set([...expenseCats,...incomeCats])];
const $=id=>document.getElementById(id);
const iso=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const today=iso(new Date());
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n||0);
const uid=()=>crypto.randomUUID();
const defaultState=()=>({version:1,transactions:[],budgets:{},recurring:[]});
let state=load(); let cloudUser=null;
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return validState(x)?x:defaultState()}catch{return defaultState()}}
function validEntry(t){return t&&typeof t.id==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(t.date)&&['income','expense'].includes(t.type)&&Number.isFinite(t.amount)&&t.amount>0&&t.amount<=1e9&&allCats.includes(t.category)&&typeof t.note==='string'&&t.note.length<=140&&typeof t.account==='string'&&t.account.length<=40}
function validState(x){return x&&x.version===1&&Array.isArray(x.transactions)&&x.transactions.length<=100000&&x.transactions.every(validEntry)&&typeof x.budgets==='object'&&x.budgets!==null&&!Array.isArray(x.budgets)&&Array.isArray(x.recurring)&&x.recurring.length<=10000&&x.recurring.every(r=>validEntry(r)&&/^\d{4}-\d{2}-\d{2}$/.test(r.nextDate))}

let toastTimer;function notify(t){const el=$('toast');el.textContent=t;el.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.style.display='none',3500)}
function addOption(sel,text,value=text){const o=document.createElement('option');o.value=value;o.textContent=text;sel.appendChild(o)}
function categories(){const select=$('category');select.replaceChildren();( $('type').value==='income'?incomeCats:expenseCats).forEach(x=>addOption(select,x));}
function selectedMonth(){return $('month').value||today.slice(0,7)}
function monthEntries(){return state.transactions.filter(t=>t.date.slice(0,7)===selectedMonth())}
function total(rows,type){return rows.filter(t=>t.type===type).reduce((sum,t)=>sum+t.amount,0)}
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el}
function refresh(){const monthly=monthEntries(),i=total(monthly,'income'),e=total(monthly,'expense');$('income').textContent=money(i);$('expense').textContent=money(e);$('net').textContent=money(i-e);$('rate').textContent=i>0?`${Math.round((i-e)/i*100)}%`:'—';renderRows();renderCategories(monthly);renderTrend();renderBudgets(monthly);renderRecurring();}
function renderRows(){const term=$('search').value.trim().toLowerCase(),type=$('filterType').value,cat=$('filterCategory').value;const arr=monthEntries().filter(t=>(type==='all'||t.type===type)&&(cat==='all'||t.category===cat)&&(!term||(t.note+' '+t.category+' '+t.account).toLowerCase().includes(term))).sort((a,b)=>b.date.localeCompare(a.date));$('count').textContent=arr.length+' shown';const body=$('rows');body.replaceChildren();$('empty').hidden=arr.length!==0;for(const t of arr){const tr=node('tr');tr.append(node('td',t.date),node('td',t.note||'—'),node('td',t.category),node('td',t.account));const badge=node('span',t.type,t.type==='expense'?'pill expense':'pill');const typeTd=node('td');typeTd.append(badge);tr.append(typeTd,node('td',money(t.amount),'number'));const action=node('td');const b=node('button','Delete','btn danger');b.type='button';b.style.padding='6px 10px';b.dataset.delete=t.id;action.append(b);tr.append(action);body.append(tr)}}
function renderCategories(rows){const data=expenseCats.map(c=>({name:c,value:rows.filter(t=>t.type==='expense'&&t.category===c).reduce((s,t)=>s+t.amount,0)})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value);const out=$('categoryBars');out.replaceChildren();if(!data.length){out.append(node('p','Add expenses to see the breakdown.','help'));return}const max=data[0].value;for(const d of data){const r=node('div',undefined,'barrow');r.append(node('span',d.name));const track=node('div',undefined,'track'),fill=node('div',undefined,'fill');fill.style.width=`${d.value/max*100}%`;track.append(fill);r.append(track,node('strong',money(d.value)));out.append(r)}}
function renderTrend(){const m=selectedMonth(),[year,month]=m.split('-').map(Number),months=Array.from({length:6},(_,j)=>{const d=new Date(year,month-1-(5-j),1);return iso(d).slice(0,7)});const vals=months.map(k=>{const tx=state.transactions.filter(x=>x.date.startsWith(k));return [total(tx,'income'),total(tx,'expense')]});const max=Math.max(1,...vals.flat()),w=480,h=190,base=150,groups=months.length;const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('role','img');svg.setAttribute('aria-label','Last six months income and expense comparison');function addSvg(tag,attrs,txt){const el=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));if(txt!==undefined)el.textContent=txt;svg.append(el)}addSvg('line',{x1:16,y1:base,x2:w-12,y2:base,stroke:'#cfd9e5'});months.forEach((m,j)=>{const x=28+j*76;vals[j].forEach((v,k)=>{const bh=v/max*120;addSvg('rect',{x:x+k*24,y:base-bh,width:20,height:Math.max(0,bh),rx:3,fill:k===0?'#14b8a6':'#e76c84'});});addSvg('text',{x:x+19,y:base+19,fill:'#77869a','text-anchor':'middle','font-size':11},new Date(m+'-02T12:00:00').toLocaleString('en-IN',{month:'short'}))});$('trendChart').replaceChildren(svg)}
function renderBudgets(rows){const host=$('budgets');host.replaceChildren();const m=selectedMonth();for(const c of expenseCats){const key=m+'|'+c,limit=Number(state.budgets[key]||0),spent=rows.filter(t=>t.type==='expense'&&t.category===c).reduce((s,t)=>s+t.amount,0);const el=node('div',undefined,'budget'+(limit>0&&spent>limit?' over':''));const top=node('div',undefined,'row'),name=node('strong',c),input=node('input');input.type='number';input.min='0';input.max='1000000000';input.step='1';input.placeholder='Set limit';input.value=limit||'';input.setAttribute('aria-label','Budget for '+c);input.addEventListener('change',async()=>{const v=Number(input.value);if(!Number.isFinite(v)||v<0||v>1e9){notify('Invalid budget');input.value=limit||'';return}try{if(cloudUser){if(v===0)await removeBudgetRemote(m,c);else await putRemote('moneytools_budgets',{user_id:cloudUser.id,month:m+'-01',category:c,amount:v},'user_id,month,category')}if(v===0)delete state.budgets[key];else state.budgets[key]=v;if(!cloudUser)saveGuest();refresh();notify('Budget saved')}catch(ex){notify('Budget update failed: '+ex.message);input.value=limit||''}});top.append(name,input);el.append(top);const info=node('div',money(spent)+(limit?' / '+money(limit):' · no limit'),'help');el.append(info);const track=node('div',undefined,'track'),bar=node('div',undefined,'fill');bar.style.width=limit?`${Math.min(100,spent/limit*100)}%`:'0%';track.append(bar);el.append(track);host.append(el)}}
function addMonths(dateString,n=1){const [y,m,d]=dateString.split('-').map(Number);const result=new Date(y,m-1+n,1);const last=new Date(result.getFullYear(),result.getMonth()+1,0).getDate();result.setDate(Math.min(d,last));return iso(result)}
async function occurrenceId(ruleId,date){const bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('kw-recurring:'+ruleId+':'+date)));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const s=Array.from(bytes.slice(0,16),b=>b.toString(16).padStart(2,'0')).join('');return s.slice(0,8)+'-'+s.slice(8,12)+'-'+s.slice(12,16)+'-'+s.slice(16,20)+'-'+s.slice(20)}
function renderRecurring(){const host=$('recurringList');host.replaceChildren();if(!state.recurring.length){host.append(node('p','No recurring entries scheduled.','help'));return}for(const r of state.recurring){const row=node('div',undefined,'row');row.style.padding='9px 0';row.append(node('span',`${r.category} · ${money(r.amount)} · ${r.nextDate}`));const b=node('button','Remove','btn danger');b.style.padding='6px 10px';b.dataset.removeRecurring=r.id;row.append(b);host.append(row)}}
function exportCSV(){const cols=['date','type','category','amount','account','note'];const escape=v=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s)&&isNaN(Number(s)))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};const lines=[cols.join(','),...state.transactions.map(x=>cols.map(c=>escape(x[c])).join(','))];download('KharchaWise_Transactions.csv',String.fromCharCode(0xFEFF)+lines.join('\r\n'),'text/csv;charset=utf-8')}
function download(filename,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
$('type').addEventListener('change',categories);
$('entryForm').addEventListener('submit',async e=>{e.preventDefault();const amount=Number($('amount').value),date=$('date').value,type=$('type').value,category=$('category').value,note=$('note').value.trim(),account=$('account').value;if(!Number.isFinite(amount)||amount<=0||amount>1e9||!/^(\d{4})-(\d{2})-(\d{2})$/.test(date)||!allCats.includes(category)){notify('Check amount, date and category');return}const tx={id:uid(),date,type,category,amount,account,note};const recurring=$('repeat').value==='monthly'?{...tx,id:uid(),nextDate:addMonths(date)}:null;if(cloudUser){try{await putRemote('moneytools_transactions',toTx(tx));if(recurring)await putRemote('moneytools_recurring',toRecurring(recurring));state.transactions.push(tx);if(recurring)state.recurring.push(recurring);setSync('Saved to cloud');}catch(ex){setSync('Cloud save failed · '+ex.message);notify('Save failed; no local change made');return}}else{state.transactions.push(tx);if(recurring)state.recurring.push(recurring);saveGuest()}e.target.reset();$('date').value=today;categories();refresh();notify('Transaction saved')});
$('rows').addEventListener('click',async e=>{const id=e.target.dataset.delete;if(!id||!confirm('Delete this transaction?'))return;try{if(cloudUser)await removeRemote('moneytools_transactions',id);state.transactions=state.transactions.filter(t=>t.id!==id);if(!cloudUser)saveGuest();refresh();notify('Deleted')}catch(ex){notify('Delete failed: '+ex.message)}});
$('recurringList').addEventListener('click',async e=>{const id=e.target.dataset.removeRecurring;if(!id||!confirm('Remove recurring rule?'))return;try{if(cloudUser)await removeRemote('moneytools_recurring',id);state.recurring=state.recurring.filter(t=>t.id!==id);if(!cloudUser)saveGuest();refresh()}catch(ex){notify('Remove failed: '+ex.message)}});
$('applyRecurring').addEventListener('click',async()=>{if(busy)return;busy=true;const items=[],updates=[];for(const r of state.recurring){let next=r.nextDate,n=0;while(next<=today&&n<120){items.push({id:await occurrenceId(r.id,next),date:next,type:r.type,category:r.category,amount:r.amount,account:r.account,note:r.note});next=addMonths(next);n++}if(n)updates.push({...r,nextDate:next})}try{if(cloudUser){for(const t of items)await putRemote('moneytools_transactions',toTx(t));for(const r of updates)await putRemote('moneytools_recurring',toRecurring(r))}state.transactions.push(...items);for(const r of updates){const i=state.recurring.findIndex(t=>t.id===r.id);if(i>=0)state.recurring[i]=r}if(!cloudUser)saveGuest();refresh();notify(items.length+' due entries applied')}catch(ex){notify('Partial cloud update; refresh cloud before retrying');setSync('Recurring sync incomplete · refresh cloud')}finally{busy=false}});
$('month').addEventListener('change',refresh);$('filterType').addEventListener('change',refresh);$('filterCategory').addEventListener('change',refresh);$('search').addEventListener('input',refresh);$('exportCsv').addEventListener('click',exportCSV);$('backup').addEventListener('click',()=>download('KharchaWise_Backup_'+today+'.json',JSON.stringify(state,null,2),'application/json'));
$('restore').addEventListener('click',()=>$('restoreFile').click());$('restoreFile').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{if(cloudUser)throw Error('Sign out before restoring a local backup');if(f.size>10000000)throw Error('Backup too large');const v=JSON.parse(await f.text());if(!validState(v))throw Error('Invalid backup schema');if(!confirm('Replace browser-only data with backup?'))return;state=v;saveGuest();refresh();notify('Restored')}catch(ex){notify(ex.message)}finally{e.target.value=''}});
$('dismissWelcome').addEventListener('click',()=>{$('welcome').hidden=true});$('date').value=today;$('month').value=today.slice(0,7);categories();allCats.forEach(c=>addOption($('filterCategory'),c));refresh();

const SUPABASE_URL='https://thkotqbeeqenpxnwfgih.supabase.co';
const SUPABASE_KEY='sb_publishable_0NQd88miUA9xj92N5hhbHA_LLWJnfDX';
const LOGIN_REDIRECT=location.origin+location.pathname;
let sb=null,busy=false;
function setSync(t){$('syncIndicator').textContent=t}
function updateAuthUI(){const signed=!!cloudUser;$('authControls').hidden=signed;$('signOutBtn').hidden=!signed;$('importLocalBtn').hidden=!signed;$('refreshCloudBtn').hidden=!signed;$('cloudStatus').textContent=signed?'Signed in: '+cloudUser.email+' · Cloud mode':'Guest mode · stored in this browser only';}
function saveGuest(){try{if(!cloudUser)localStorage.setItem(KEY,JSON.stringify(state));return true}catch{notify('Local storage unavailable; export backup');return false}}
const toTx=t=>({id:t.id,user_id:cloudUser.id,entry_date:t.date,entry_type:t.type,category:t.category,amount:t.amount,account:t.account,note:t.note});
const toRecurring=t=>({...toTx(t),next_date:t.nextDate});
async function putRemote(table,record,onConflict='id'){const {error}=await sb.from(table).upsert(record,{onConflict});if(error)throw error}
async function removeRemote(table,id){const {error}=await sb.from(table).delete().eq('id',id).eq('user_id',cloudUser.id);if(error)throw error}
async function removeBudgetRemote(m,c){const {error}=await sb.from('moneytools_budgets').delete().eq('month',m+'-01').eq('category',c).eq('user_id',cloudUser.id);if(error)throw error}
async function allRows(table){const results=[];for(let offset=0;offset<50000;offset+=500){let q=sb.from(table).select('*');q=table==='moneytools_budgets'?q.order('month').order('category'):q.order('id');const {data,error}=await q.range(offset,offset+499);if(error)throw error;results.push(...data);if(data.length<500)return results}throw Error('Dataset too large; export from dashboard')}
async function readCloud(){if(!cloudUser||busy)return;busy=true;const forUser=cloudUser.id;setSync('Loading cloud records…');try{const [tx,b,rec]=await Promise.all([allRows('moneytools_transactions'),allRows('moneytools_budgets'),allRows('moneytools_recurring')]);if(!cloudUser||cloudUser.id!==forUser)return;state={version:1,transactions:tx.map(x=>({id:x.id,date:x.entry_date,type:x.entry_type,category:x.category,amount:Number(x.amount),account:x.account,note:x.note})),budgets:Object.fromEntries(b.map(x=>[x.month.slice(0,7)+'|'+x.category,Number(x.amount)])),recurring:rec.map(x=>({id:x.id,date:x.entry_date,nextDate:x.next_date,type:x.entry_type,category:x.category,amount:Number(x.amount),account:x.account,note:x.note}))};refresh();setSync('Cloud data loaded · '+new Date().toLocaleTimeString())}catch(ex){setSync('Cloud read failed: '+ex.message);notify('Cloud read failed')}finally{busy=false}}
async function accountAction(mode){if(!sb){notify('Cloud client unavailable');return}const email=$('authEmail').value.trim(),password=$('authPassword').value;if(!email||password.length<8)return notify('Use email and password (8+ characters)');setSync('Authenticating…');try{const {data,error}=mode==='signup'?await sb.auth.signUp({email,password,options:{emailRedirectTo:LOGIN_REDIRECT}}):await sb.auth.signInWithPassword({email,password});if(error)throw error;setSync(mode==='signup'&&!data.session?'Check email verification. Public sign-ups may require SMTP setup.':'Signed in');$('authPassword').value=''}catch(ex){setSync('Login error: '+ex.message)}}
async function signedIn(user){if(cloudUser?.id===user.id)return;cloudUser=user;state=defaultState();updateAuthUI();refresh();await readCloud()}
async function signedOut(){cloudUser=null;state=load();updateAuthUI();refresh();setSync('Signed out · guest mode')}
async function initialiseCloud(){try{const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.58.0/+esm');sb=mod.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});sb.auth.onAuthStateChange((event,session)=>{setTimeout(()=>{if(event==='SIGNED_OUT')signedOut();else if(session?.user)signedIn(session.user)},0)});const {data,error}=await sb.auth.getSession();if(error)throw error;if(data.session?.user)await signedIn(data.session.user);else updateAuthUI()}catch(ex){setSync('Cloud client unavailable: '+ex.message)}}
$('signInBtn').addEventListener('click',()=>accountAction('signin'));
$('signUpBtn').addEventListener('click',()=>accountAction('signup'));
$('signOutBtn').addEventListener('click',async()=>{if(busy)return notify('An operation is running');try{const {error}=await sb.auth.signOut({scope:'local'});if(error)throw error;await signedOut()}catch(e){setSync('Sign out failed: '+e.message)}});
$('refreshCloudBtn').addEventListener('click',()=>readCloud());
$('importLocalBtn').addEventListener('click',async()=>{if(!cloudUser||busy)return;const guest=load();if(!validState(guest))return notify('No valid browser-only data');if(!confirm('Import browser-only transactions, budgets and recurring entries into your cloud account?'))return;busy=true;try{const tIds=new Set(state.transactions.map(t=>t.id));for(const t of guest.transactions){if(!tIds.has(t.id)){await putRemote('moneytools_transactions',toTx(t));tIds.add(t.id)}}for(const [k,v] of Object.entries(guest.budgets)){if(!(k in state.budgets)&&Number(v)>0){const [m,c]=k.split('|');await putRemote('moneytools_budgets',{user_id:cloudUser.id,month:m+'-01',category:c,amount:v},'user_id,month,category')}}const rIds=new Set(state.recurring.map(t=>t.id));for(const r of guest.recurring){if(!rIds.has(r.id)){await putRemote('moneytools_recurring',toRecurring(r));rIds.add(r.id)}}setSync('Import complete. Refreshing cloud…')}catch(ex){setSync('Import incomplete: '+ex.message)}finally{busy=false;await readCloud()}});
initialiseCloud();
