// KharchaWise: free, account-only personal finance dashboard.
// The only embedded API key is Supabase's intended PUBLIC publishable key.
// Row ownership is enforced by PostgreSQL RLS, never by browser code alone.
const SUPABASE_URL='https://thkotqbeeqenpxnwfgih.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_0NQd88miUA9xj92N5hhbHA_LLWJnfDX';
const TABLES={transactions:'moneytools_transactions',budgets:'moneytools_budgets',recurring:'moneytools_recurring'};
const INCOME=['Salary','Business','Freelance','Interest','Investment','Gift','Other Income'];
const EXPENSE=['Food','Rent','Groceries','Travel','Shopping','Bills','Education','Health','EMI','Entertainment','Family','Savings','Other'];
const ICONS={Salary:'₹',Business:'▣',Freelance:'◇',Food:'☕',Rent:'⌂',Groceries:'▤',Travel:'✈',Shopping:'▣',Bills:'◈',Education:'▧',Health:'✚',EMI:'◉',Entertainment:'♫',Savings:'◎',Other:'◇'};
const $=id=>document.getElementById(id);
const formatINR=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2});
const money=n=>formatINR.format(Number(n)||0);
const uuid=()=>crypto.randomUUID?.()||'10000000-1000-4000-8000-100000000000'.replace(/[018]/g,c=>(Number(c)^crypto.getRandomValues(new Uint8Array(1))[0]&(15>>Number(c)/4)).toString(16));
const todayLocal=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const currentMonth=()=> $('monthSelect').value||todayLocal().slice(0,7);
let sb=null,user=null,active='overview',mode='signin',editingId=null,loading=false,toastTimer=null,pageNum=0,recovering=/[?&#]type=recovery(?:&|$)/.test(location.href);
let state={transactions:[],budgets:[],recurring:[]};
function message(text,error=false){const el=$('toast');el.textContent=text;el.classList.toggle('error',error);el.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.style.display='none',4500)}
function sync(text,variant=''){const el=$('cloudIndicator');el.className='sync'+(variant?' '+variant:'');el.lastChild.textContent=' '+text}
function switchPage(page){if(!['overview','transactions','budgets','recurring','data'].includes(page))return;active=page;document.querySelectorAll('[data-panel]').forEach(el=>el.classList.toggle('hidden',el.dataset.panel!==page));document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===page));const names={overview:['YOUR FINANCIAL SNAPSHOT','Your money, made clear.'],transactions:['YOUR COMPLETE HISTORY','Transactions'],budgets:['SET YOUR LIMITS','Monthly budgets'],recurring:['PLAN AHEAD','Recurring payments'],data:['ACCOUNT & PRIVACY','My data & downloads']};$('pageEyebrow').textContent=names[page][0];$('pageTitle').textContent=names[page][1];window.scrollTo({top:0,behavior:'instant'});render();}
function setAuthMode(next){mode=next;$('authTitle').textContent=next==='signup'?'Start tracking for free':next==='reset'?'Reset your password':'Welcome back';$('authSubtitle').textContent=next==='signup'?'Create your private account. No card required.':next==='reset'?'We will email you a password reset link.':'Sign in to access your personal money dashboard.';$('passwordWrap').classList.toggle('hidden',next==='reset');$('authPassword').required=next!=='reset';$('authSubmit').firstChild.textContent=next==='signup'?'Create free account ':next==='reset'?'Send reset email ':'Sign in securely ';$('switchAuth').textContent=next==='signin'?'Create a free account':'Back to sign in';$('forgotPassword').classList.toggle('hidden',next==='reset');$('authStatus').textContent='';}
function clearPrivateData(){state={transactions:[],budgets:[],recurring:[]};user=null;editingId=null;pageNum=0;$('userLabel').textContent='My account';$('accountEmail').textContent='—'}
function showAuth(){clearPrivateData();$('loading').classList.add('hidden');$('appPage').classList.add('hidden');$('authPage').classList.remove('hidden');const recovery=$('recoveryForm');if(recovery)recovery.remove();$('authForm').classList.remove('hidden');document.querySelector('.auth-links').classList.remove('hidden');sync('Signed out');}
function showRecovery(){
 recovering=true;clearPrivateData();$('loading').classList.add('hidden');$('appPage').classList.add('hidden');$('authPage').classList.remove('hidden');
 $('authForm').classList.add('hidden');document.querySelector('.auth-links').classList.add('hidden');$('authTitle').textContent='Set your new password';$('authSubtitle').textContent='Your secure recovery link is active. Choose a new password for your account.';
 if($('recoveryForm'))return;
 const form=document.createElement('form');form.id='recoveryForm';
 const lbl=document.createElement('label');lbl.htmlFor='newPassword';lbl.textContent='New password (minimum 12 characters)';
 const input=document.createElement('input');input.type='password';input.id='newPassword';input.autocomplete='new-password';input.minLength=12;input.maxLength=128;input.required=true;
 const confirmLabel=document.createElement('label');confirmLabel.htmlFor='confirmNewPassword';confirmLabel.textContent='Confirm new password';
 const confirmInput=document.createElement('input');confirmInput.type='password';confirmInput.id='confirmNewPassword';confirmInput.autocomplete='new-password';confirmInput.required=true;
 const button=document.createElement('button');button.type='submit';button.className='button primary full';button.textContent='Save new password';
 form.append(lbl,input,confirmLabel,confirmInput,button);$('authForm').after(form);
 form.addEventListener('submit',async e=>{e.preventDefault();$('authStatus').textContent='Updating password…';button.disabled=true;try{
 if(input.value!==confirmInput.value)throw Error('Passwords do not match');
 const {data,error:authError}=await sb.auth.getUser();if(authError||!data.user)throw Error('Recovery link expired. Request a new one.');
 const {error}=await sb.auth.updateUser({password:input.value});if(error)throw error;
 recovering=false;const {error:signoutError}=await sb.auth.signOut({scope:'global'});if(signoutError)throw signoutError;
 if(location.protocol==='https:'||location.protocol==='http:')history.replaceState(null,'',location.pathname);showAuth();setAuthMode('signin');$('authStatus').textContent='Password updated. Sign in with your new password.';
 }catch(err){$('authStatus').textContent='Could not update password: '+err.message}finally{button.disabled=false;input.value='';confirmInput.value=''}});
}
async function showApp(sessionUser){if(recovering)return;if(user?.id===sessionUser.id)return;clearPrivateData();user=sessionUser;$('accountEmail').textContent=user.email||'Account';$('userLabel').textContent=user.email||'My account';$('avatar').textContent=(user.email||'U')[0].toUpperCase();$('loading').classList.add('hidden');$('authPage').classList.add('hidden');$('appPage').classList.remove('hidden');await loadCloud();}
async function verifiedUser(){if(!sb||!user)throw Error('Sign in is required');const id=user.id;const {data,error}=await sb.auth.getUser();if(error||!data?.user||data.user.id!==id)throw Error('Session expired. Sign in again.');return id;}
function startBusy(){if(loading)throw Error('Another operation is in progress');loading=true;sync('Working…');}
function endBusy(){loading=false;}
async function allRows(name,owner,order='id'){
 const list=[];for(let offset=0;offset<50000;offset+=500){let query=sb.from(name).select('*').eq('user_id',owner);if(name===TABLES.budgets){query=query.order('month',{ascending:true}).order('category',{ascending:true})}else{query=query.order('id',{ascending:true})}query=query.range(offset,offset+499);const {data,error}=await query;if(error)throw Error(error.message);list.push(...(data||[]));if((data||[]).length<500)return list;}throw Error('Too many records for a single export. Contact support.');
}
async function freshOwnData(){const owner=await verifiedUser();const [tx,bud,rec]=await Promise.all([allRows(TABLES.transactions,owner),allRows(TABLES.budgets,owner,'category'),allRows(TABLES.recurring,owner)]);if(!user||user.id!==owner)throw Error('Account changed while loading');return {owner,transactions:tx,budgets:bud,recurring:rec};}
async function loadCloud(){if(!user)return;try{startBusy();const v=await freshOwnData();state={transactions:v.transactions,budgets:v.budgets,recurring:v.recurring};pageNum=0;render();sync('Cloud synced','synced');}catch(e){sync('Sync failed','failed');message('Unable to refresh account data: '+e.message,true);}finally{endBusy();}}
function txInMonth(){const m=currentMonth();return state.transactions.filter(x=>x.entry_date?.slice(0,7)===m)}
function sum(list,type){return Math.round(list.filter(x=>x.entry_type===type).reduce((a,x)=>a+Number(x.amount||0),0)*100)/100}
function dom(tag,txt,cls){const el=document.createElement(tag);if(txt!==undefined)el.textContent=String(txt);if(cls)el.className=cls;return el;}
function displayDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))return s||'—';const [y,m,d]=s.split('-');return `${d} ${new Date(Number(y),Number(m)-1,1).toLocaleString('en-IN',{month:'short'})} ${y}`}
function render(){if(!user)return;const list=txInMonth(),inc=sum(list,'income'),expense=sum(list,'expense'),remain=inc-expense;$('incomeValue').textContent=money(inc);$('expenseValue').textContent=money(expense);$('balanceValue').textContent=money(remain);$('balanceLabel').textContent=remain<0?'Spending exceeds income':'Income minus expenses';$('savingRate').textContent=inc>0?`${Math.round(remain/inc*100)}%`:'—';renderFlow();renderCategories();renderRecent();renderTransactions();renderBudgets();renderRecurring();}
function renderFlow(){const [y,m]=currentMonth().split('-').map(Number);const months=Array.from({length:6},(_,i)=>{const d=new Date(y,m-6+i,1);return {month:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,label:d.toLocaleString('en-IN',{month:'short'})}});const values=months.map(x=>{const t=state.transactions.filter(k=>k.entry_date?.slice(0,7)===x.month);return [sum(t,'income'),sum(t,'expense')]});const max=Math.max(1,...values.flat());const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 620 226');svg.setAttribute('role','img');svg.setAttribute('aria-label','Income and expense comparison for the last six months');function add(tag,attrs,label){const e=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,String(v)));if(label)e.textContent=label;svg.append(e);}for(let i=0;i<4;i++)add('line',{x1:32,y1:25+i*47,x2:596,y2:25+i*47,stroke:'#e9edf3','stroke-width':1});months.forEach((x,i)=>{const left=61+i*91;values[i].forEach((val,j)=>{const height=val/max*155;add('rect',{x:left+j*24,y:169-height,width:18,height:Math.max(height,0),rx:5,fill:j?'#f17b6b':'#11ae97'});});add('text',{x:left+19,y:200,'text-anchor':'middle',fill:'#8593a2','font-size':12},x.label);});$('flowChart').replaceChildren(svg)}
function renderCategories(){const list=txInMonth().filter(x=>x.entry_type==='expense');const groups=new Map();for(const x of list)groups.set(x.category,(groups.get(x.category)||0)+Number(x.amount));const ranked=[...groups.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5);const host=$('categoryChart');host.replaceChildren();if(!ranked.length){host.append(dom('p','Start adding expenses to see your category breakdown.','empty'));return;}const max=ranked[0][1];for(const [cat,n] of ranked){const row=dom('div',undefined,'cat-row'),line=dom('div',undefined,'cat-line'),track=dom('div',undefined,'progress'),fill=dom('span');line.append(dom('span',cat),dom('strong',money(n)));fill.style.width=`${(n/max)*100}%`;track.append(fill);row.append(line,track);host.append(row)}}
function recentNode(x){const row=dom('div',undefined,'recent-line');row.append(dom('span',ICONS[x.category]||'◇','category-avatar'));const info=dom('div',undefined,'desc');info.append(dom('strong',x.note||x.category),dom('span',`${x.category} · ${displayDate(x.entry_date)} · ${x.account}`));row.append(info,dom('strong',(x.entry_type==='expense'?'− ':'+ ')+money(x.amount),'amt '+(x.entry_type==='expense'?'expense':'')));return row}
function renderRecent(){const host=$('recentList');host.replaceChildren();const arr=[...txInMonth()].sort((a,b)=>b.entry_date.localeCompare(a.entry_date)).slice(0,5);if(!arr.length){host.append(dom('p','No activity yet. Add your first transaction to get started.','empty'));return}arr.forEach(x=>host.append(recentNode(x)))}
function renderTransactions(){const search=$('searchTransactions').value.trim().toLowerCase(),filter=$('typeFilter').value,category=$('categoryFilter').value;let arr=txInMonth().filter(t=>(filter==='all'||t.entry_type===filter)&&(category==='all'||t.category===category)&&(!search||[t.note,t.category,t.account].join(' ').toLowerCase().includes(search))).sort((a,b)=>b.entry_date.localeCompare(a.entry_date)||b.created_at?.localeCompare(a.created_at||'')||0);const maxPages=Math.max(1,Math.ceil(arr.length/15));pageNum=Math.min(pageNum,maxPages-1);arr=arr.slice(pageNum*15,(pageNum+1)*15);const tbody=$('transactionRows');tbody.replaceChildren();$('transactionEmpty').classList.toggle('hidden',arr.length>0);for(const t of arr){const tr=dom('tr');tr.append(dom('td',displayDate(t.entry_date)),dom('td',t.note||t.category),dom('td',t.category),dom('td',t.account));const typ=dom('td'),badge=dom('span',t.entry_type,t.entry_type==='income'?'type-tag income':'type-tag');typ.append(badge);tr.append(typ,dom('td',money(t.amount),'right'));const act=dom('td',undefined,'right');const edit=dom('button','Edit','icon-action'),del=dom('button','Delete','icon-action red');edit.setAttribute('aria-label','Edit transaction');del.setAttribute('aria-label','Delete transaction');edit.addEventListener('click',()=>openEntry(t));del.addEventListener('click',()=>deleteTx(t.id));act.append(edit,dom('span',' '),del);tr.append(act);tbody.append(tr)}const nav=$('pagination');nav.replaceChildren();const prev=dom('button','← Previous');prev.disabled=pageNum===0;prev.addEventListener('click',()=>{pageNum--;renderTransactions()});const next=dom('button','Next →');next.disabled=pageNum>=maxPages-1;next.addEventListener('click',()=>{pageNum++;renderTransactions()});nav.append(prev,dom('span',`Page ${pageNum+1} of ${maxPages}`),next);}
function renderBudgets(){const m=currentMonth(),tx=txInMonth(),map=new Map(state.budgets.filter(b=>b.month?.slice(0,7)===m).map(b=>[b.category,Number(b.amount)]));const spend=new Map();for(const x of tx)if(x.entry_type==='expense')spend.set(x.category,(spend.get(x.category)||0)+Number(x.amount));const spent=[...spend.values()].reduce((a,b)=>a+b,0),limit=[...map.values()].reduce((a,b)=>a+b,0);$('budgetSpent').textContent=money(spent);$('budgetLimit').textContent=money(limit);$('budgetAvailable').textContent=limit?money(limit-spent):'Not set';const host=$('budgetList');host.replaceChildren();for(const cat of EXPENSE){const cap=map.get(cat)||0,cost=spend.get(cat)||0;const panel=dom('article',undefined,'budget-card'+(cap>0&&cost>cap?' over':''));const top=dom('div',undefined,'budget-card-top'),name=dom('h3',cat),label=dom('label','Limit (₹)'),input=dom('input');input.type='number';input.step='.01';input.min='0';input.max='1000000000';input.placeholder='0';input.value=cap||'';input.setAttribute('aria-label','Monthly budget for '+cat);input.addEventListener('change',()=>saveBudget(cat,m,input,cap));label.append(input);top.append(name,label);const figs=dom('div',undefined,'budget-figures');figs.append(dom('span',`${money(cost)} spent`),dom('strong',cap?`${money(Math.max(0,cap-cost))} left`:'No budget'));const progress=dom('div',undefined,'progress'),fill=dom('span');fill.style.width=cap?Math.min(cost/cap*100,100)+'%':'0%';progress.append(fill);panel.append(top,figs,progress);host.append(panel)}}
function renderRecurring(){const host=$('recurringRows');host.replaceChildren();$('recurringCount').textContent=`${state.recurring.length} schedules`;if(!state.recurring.length){host.append(dom('p','No recurring schedules. Create a monthly transaction to add one.','empty'));return}for(const r of [...state.recurring].sort((a,b)=>a.next_date.localeCompare(b.next_date))){const row=recentNode({...r,entry_date:r.next_date});const del=dom('button','Remove','icon-action red');del.addEventListener('click',()=>deleteRecurring(r.id));row.append(del);host.append(row)}}
function refreshCategorySelect(){const select=$('entryCategory');select.replaceChildren();( $('entryType').value==='income'?INCOME:EXPENSE).forEach(cat=>{const opt=document.createElement('option');opt.value=cat;opt.textContent=cat;select.append(opt)})}
function openEntry(t=null){if(!user)return message('Sign in first',true);editingId=t?.id||null;$('entryTitle').textContent=t?'Edit transaction':'Add a transaction';$('entryType').value=t?.entry_type||'expense';refreshCategorySelect();$('entryAmount').value=t?Number(t.amount):'';$('entryDate').value=t?.entry_date||todayLocal();$('entryCategory').value=t?.category||($('entryType').value==='income'?INCOME[0]:EXPENSE[0]);$('entryAccount').value=t?.account||'UPI';$('entryNote').value=t?.note||'';$('entryRepeat').value='no';$('entryRepeat').disabled=!!t;$('entryDialog').showModal();}
function parseAmount(n){const v=Number(n);if(!Number.isFinite(v)||v<0||v>1000000000)throw Error('Invalid amount');return Math.round(v*100)/100}
async function saveEntry(ev){ev.preventDefault();const id=editingId||uuid(),kind=$('entryType').value,cat=$('entryCategory').value,amount=parseAmount($('entryAmount').value),date=$('entryDate').value,note=$('entryNote').value.trim(),account=$('entryAccount').value;if(!amount||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!['income','expense'].includes(kind)||!(kind==='income'?INCOME:EXPENSE).includes(cat)||note.length>140||account.length>40){message('Check the amount, date and category.',true);return}const repeating=!editingId&&$('entryRepeat').value==='yes';const row={id,entry_date:date,entry_type:kind,category:cat,amount,account,note};try{startBusy();const owner=await verifiedUser();const {error}=await sb.from(TABLES.transactions).upsert({...row,user_id:owner},{onConflict:'id'});if(error)throw error;if(repeating){const next=addMonths(date,1);const {error:e}=await sb.from(TABLES.recurring).insert({id:uuid(),user_id:owner,entry_date:date,next_date:next,entry_type:kind,category:cat,amount,account,note});if(e)message('Transaction saved, but recurring rule failed: '+e.message,true)}$('entryDialog').close();sync('Saved to cloud','synced');message(editingId?'Transaction updated':'Transaction saved');}catch(e){message('Save failed: '+e.message,true);sync('Save failed','failed')}finally{endBusy();await loadCloud()}}
async function deleteTx(id){if(!window.confirm('Delete this transaction from your private account?'))return;try{startBusy();const owner=await verifiedUser();const {error}=await sb.from(TABLES.transactions).delete().eq('id',id).eq('user_id',owner);if(error)throw error;message('Transaction deleted')}catch(e){message('Delete failed: '+e.message,true)}finally{endBusy();await loadCloud()}}
async function saveBudget(cat,month,input,previous){try{if(loading)throw Error('Finish the previous action');const v=parseAmount(input.value||0);startBusy();const owner=await verifiedUser();if(v===0){const {error}=await sb.from(TABLES.budgets).delete().eq('user_id',owner).eq('month',month+'-01').eq('category',cat);if(error)throw error;}else{const {error}=await sb.from(TABLES.budgets).upsert({user_id:owner,month:month+'-01',category:cat,amount:v},{onConflict:'user_id,month,category'});if(error)throw error;}message('Budget updated');}catch(e){input.value=previous||'';message('Budget error: '+e.message,true)}finally{endBusy();await loadCloud()}}
function addMonths(date,n=1){const [y,m,d]=date.split('-').map(Number),dt=new Date(y,m-1+n,1),last=new Date(dt.getFullYear(),dt.getMonth()+1,0).getDate();return `${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}-${String(Math.min(d,last)).padStart(2,'0')}`}
async function deleteRecurring(id){if(!confirm('Remove this recurring schedule?'))return;try{startBusy();const owner=await verifiedUser();const {error}=await sb.from(TABLES.recurring).delete().eq('id',id).eq('user_id',owner);if(error)throw error;message('Schedule removed')}catch(e){message('Unable to remove schedule: '+e.message,true)}finally{endBusy();await loadCloud()}}
async function occurrenceId(ruleId,date){const data=new TextEncoder().encode('kw-recurring:'+ruleId+':'+date);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data)).slice(0,16));hash[6]=(hash[6]&15)|64;hash[8]=(hash[8]&63)|128;const h=hash.map(n=>n.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`}
async function applyDue(){if(!confirm('Create all due monthly entries through today? No payment will be charged.'))return;try{startBusy();const owner=await verifiedUser();let count=0;for(const rule of state.recurring){let date=rule.next_date,iterations=0;while(date<=todayLocal()&&iterations++<120){const id=await occurrenceId(rule.id,date);const row={id,user_id:owner,entry_date:date,entry_type:rule.entry_type,category:rule.category,amount:rule.amount,account:rule.account,note:rule.note};const {error}=await sb.from(TABLES.transactions).upsert(row,{onConflict:'id'});if(error)throw error;date=addMonths(date,1);const {error:err}=await sb.from(TABLES.recurring).update({next_date:date}).eq('id',rule.id).eq('user_id',owner);if(err)throw err;count++;}if(iterations>120)throw Error('Recurring rule needs manual review')}message(`${count} scheduled entries applied. No bank payment was made.`)}catch(e){message('Recurring update incomplete: '+e.message,true)}finally{endBusy();await loadCloud()}}
const columns={transactions:['entry_date','entry_type','category','amount','account','note'],budgets:['month','category','amount'],recurring:['entry_date','next_date','entry_type','category','amount','account','note']};
function quoteCSV(val){let str=String(val??'');if(/^[\s\u0000-\u001f]*[=+@\-]/.test(str)&&(!/^[-+]?\d+(?:\.\d+)?$/.test(str.trim())))str="'"+str;return '"'+str.replaceAll('"','""')+'"';}
function blobDownload(name,body,mime){const url=URL.createObjectURL(new Blob([body],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function asCsv(rows,type){const keys=columns[type];return '\ufeff'+[keys.join(','),...rows.map(x=>keys.map(k=>quoteCSV(x[k])).join(','))].join('\r\n')}
async function downloadMine(which){try{startBusy();const raw=await freshOwnData();const date=todayLocal();if(which==='all'){const payload={format:'KharchaWise Backup',schemaVersion:2,exportedAt:new Date().toISOString(),ownerEmail:user.email,transactions:raw.transactions.map(({user_id,...r})=>r),budgets:raw.budgets.map(({user_id,...r})=>r),recurring:raw.recurring.map(({user_id,...r})=>r)};blobDownload(`KharchaWise_My_Data_${date}.json`,JSON.stringify(payload,null,2),'application/json')}else{blobDownload(`KharchaWise_${which}_${date}.csv`,asCsv(raw[which],which),'text/csv;charset=utf-8')}message('Your private account data was downloaded successfully');}catch(e){message('Download failed: '+e.message,true)}finally{endBusy();sync('Cloud synced','synced')}}
function validUUID(s){return typeof s==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s)}
function checkImport(data){if(data?.format!=='KharchaWise Backup'||data.schemaVersion!==2)throw Error('Not a compatible KharchaWise backup');for(const type of Object.keys(columns)){const rows=data[type];if(!Array.isArray(rows)||rows.length>5000)throw Error('Invalid '+type+' rows (max 5000)');for(const row of rows){if(!row||typeof row!=='object')throw Error('Malformed row');if(!Object.keys(row).every(k=>[...columns[type],'id','created_at'].includes(k)))throw Error('Unexpected field in '+type);if(type!=='budgets'&&!validUUID(row.id))throw Error('Invalid record ID');if(!Number.isFinite(Number(row.amount))||Number(row.amount)<(type==='budgets'?0:0.01)||Number(row.amount)>1e9)throw Error('Invalid amount');if(typeof row.category!=='string'||row.category.length>80||!row.category.trim())throw Error('Invalid category');if(type==='budgets'){if(!/^\d{4}-\d{2}-01$/.test(row.month))throw Error('Invalid budget month')}else{if(!/^\d{4}-\d{2}-\d{2}$/.test(row.entry_date)||!['income','expense'].includes(row.entry_type)||typeof row.account!=='string'||row.account.length>40||typeof row.note!=='string'||row.note.length>140)throw Error('Invalid transaction fields');if(type==='recurring'&&!/^\d{4}-\d{2}-\d{2}$/.test(row.next_date))throw Error('Invalid recurring date')}}}return data}
async function importMine(file){try{if(!file||file.size>5e6)throw Error('Choose a JSON file under 5 MB');const data=checkImport(JSON.parse(await file.text()));const counts=Object.keys(columns).map(k=>`${data[k].length} ${k}`).join(', ');if(!confirm(`Import ${counts} into your OWN account? Existing matching records may be updated, but no other records will be deleted.`))return;startBusy();const owner=await verifiedUser();for(const type of Object.keys(columns)){const allowed=type==='budgets'?[...columns[type]]:['id',...columns[type]];for(let n=0;n<data[type].length;n+=100){const batch=data[type].slice(n,n+100).map(src=>{const rec={user_id:owner};for(const key of allowed)rec[key]=src[key];if('amount' in rec)rec.amount=parseAmount(rec.amount);return rec;});if(!batch.length)continue;const unique=type==='budgets'?'user_id,month,category':'id';const {error}=await sb.from(TABLES[type]).upsert(batch,{onConflict:unique});if(error)throw error;}}message('Backup successfully imported into your account');}catch(e){message('Import failed (partial import possible): '+e.message,true)}finally{endBusy();await loadCloud();$('backupFile').value=''}}
async function deleteAll(){if(prompt('This permanently deletes your transactions, budgets and recurring schedules. Type DELETE to confirm:')!=='DELETE')return;try{startBusy();const owner=await verifiedUser();for(const table of [TABLES.transactions,TABLES.budgets,TABLES.recurring]){let query=sb.from(table).delete().eq('user_id',owner);const {error}=await query;if(error)throw error;}message('All your KharchaWise records have been deleted');}catch(e){message('Deletion incomplete: '+e.message,true)}finally{endBusy();await loadCloud()}}
function bind(){const to=p=>switchPage(p);$('nav').addEventListener('click',e=>{const btn=e.target.closest('[data-page]');if(btn)to(btn.dataset.page)});document.querySelectorAll('[data-goto]').forEach(b=>b.addEventListener('click',()=>to(b.dataset.goto)));$('monthSelect').value=todayLocal().slice(0,7);$('monthSelect').addEventListener('change',()=>{pageNum=0;render()});$('quickAddBtn').addEventListener('click',()=>openEntry());$('addTransactionPage').addEventListener('click',()=>openEntry());$('closeDialog').addEventListener('click',()=>$('entryDialog').close());$('cancelDialog').addEventListener('click',()=>$('entryDialog').close());$('entryType').addEventListener('change',refreshCategorySelect);$('entryForm').addEventListener('submit',saveEntry);$('searchTransactions').addEventListener('input',()=>{pageNum=0;renderTransactions()});$('typeFilter').addEventListener('change',()=>{pageNum=0;renderTransactions()});const catSel=$('categoryFilter');catSel.replaceChildren(new Option('All categories','all'));for(const name of [...new Set([...INCOME,...EXPENSE])])catSel.add(new Option(name,name));catSel.addEventListener('change',()=>{pageNum=0;renderTransactions()});$('applyDueBtn').addEventListener('click',applyDue);$('exportTxBtn').addEventListener('click',()=>downloadMine('transactions'));$('downloadAllBtn').addEventListener('click',()=>downloadMine('all'));$('downloadCsvBtn').addEventListener('click',()=>downloadMine('transactions'));$('downloadBudgetsBtn').addEventListener('click',()=>downloadMine('budgets'));$('downloadRecurringBtn').addEventListener('click',()=>downloadMine('recurring'));$('importBtn').addEventListener('click',()=>$('backupFile').click());$('backupFile').addEventListener('change',e=>importMine(e.target.files?.[0]));$('deleteAllBtn').addEventListener('click',deleteAll);$('resetPasswordBtn').addEventListener('click',async()=>{if(!user?.email)return;try{const {error}=await sb.auth.resetPasswordForEmail(user.email,{redirectTo:location.origin+location.pathname});if(error)throw error;message('Reset email requested. Email delivery may be limited during private beta.')}catch(e){message(e.message,true)}});$('signOutBtn').addEventListener('click',async()=>{try{const {error}=await sb.auth.signOut();if(error)throw error;showAuth();}catch(e){message('Sign out failed: '+e.message,true)}});$('switchAuth').addEventListener('click',()=>setAuthMode(mode==='signin'?'signup':'signin'));$('forgotPassword').addEventListener('click',()=>setAuthMode('reset'));
$('authForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('authEmail').value.trim(),password=$('authPassword').value,button=$('authSubmit');button.disabled=true;$('authStatus').textContent='Working…';try{if(mode==='reset'){const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)throw error;$('authStatus').textContent='If the address is eligible, a reset email will arrive. Email delivery may be restricted during beta.';}else if(mode==='signup'){const {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error;$('authStatus').textContent=data.session?'Account created. Loading dashboard…':'Please verify your email first. Default Supabase email is restricted to approved recipients.';if(data.session?.user)await showApp(data.session.user);}else{const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;if(data.user)await showApp(data.user);}$('authPassword').value=''}catch(e){$('authStatus').textContent=e.message||'Authentication failed'}finally{button.disabled=false}});
}
async function init(){bind();try{const pkg=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.58.0/+esm');sb=pkg.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});sb.auth.onAuthStateChange((event,session)=>{setTimeout(()=>{if(event==='PASSWORD_RECOVERY')showRecovery();else if(event==='SIGNED_OUT'&&!recovering)showAuth();else if(event==='SIGNED_IN'&&!recovering&&session?.user&&session.user.id!==user?.id)showApp(session.user)},0)});const {data:{user:authenticated},error}=await sb.auth.getUser();if(recovering&&authenticated)showRecovery();else if(error||!authenticated){const recoveryWasRequested=recovering;recovering=false;showAuth();if(recoveryWasRequested)$('authStatus').textContent='Recovery link expired or invalid. Request a new one.';}else await showApp(authenticated);}catch(e){showAuth();$('authStatus').textContent='Cloud service unavailable: '+e.message;}}
init();
